Init

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -271,14 +271,39 @@ jobs:
       - run:
           name: Install dependencies
           command: |
-            # your code here
-            apk add --update ansible 
-            apk add --update nodejs npm
+            pip install ansible
+            pip install awscli
+            apt update && apt install nodejs npm tar gzip -y
+      - run:
+          name: Add ENV
+          command: |
+            echo "NODE_ENV=$NODE_ENV" >> backend/.env
+            echo "VERSION=$VERSION" >> backend/.env
+            echo "TYPEORM_CONNECTION=$TYPEORM_CONNECTION" >> backend/.env
+            echo "TYPEORM_MIGRATIONS_DIR=$TYPEORM_MIGRATIONS_DIR" >> backend/.env
+            echo "TYPEORM_ENTITIES=$TYPEORM_ENTITIES" >> backend/.env
+            echo "TYPEORM_MIGRATIONS=$TYPEORM_MIGRATIONS" >> backend/.env
+            echo "TYPEORM_HOST=$TYPEORM_HOST" >> backend/.env
+            echo "TYPEORM_PORT=$TYPEORM_PORT" >> backend/.env
+            echo "TYPEORM_USERNAME=$TYPEORM_USERNAME" >> backend/.env
+            echo "TYPEORM_PASSWORD=$TYPEORM_PASSWORD" >> backend/.env
+            echo "TYPEORM_DATABASE=$TYPEORM_DATABASE" >> backend/.env
+            echo "--------cat .env--------"
+            cat backend/.env
       - run:
           name: Deploy backend
           command: |
             # your code here
-      # Here's where you will add some code to rollback on failure  
+            cd backend
+            npm i
+            npm run build
+            cd ..
+            # Zip the directory
+            tar -C backend -czvf artifact.tar.gz .
+            cd .circleci/ansible
+            echo "Contents  of the inventory.txt file is -------"
+            cat inventory.txt
+            ansible-playbook -i inventory.txt deploy-backend.yml 
 
   smoke-test:
     docker:
@@ -288,19 +313,37 @@ jobs:
       - run:
           name: Install dependencies
           command: |
-            # your code here
-      - run:
-          name: Get backend url
-          command: |
-            # your code here
+            pip install ansible
+            pip install awscli
+            apt update && apt install nodejs npm tar gzip -y
+      - attach_workspace:
+          at: ~/
       - run:
           name: Backend smoke test.
           command: |
-            # your code here
+            export BACKEND_IP=$(cat ~/inventory.txt)
+            export API_URL=http://$BACKEND_IP:3030
+            echo $API_URL
+            if curl "$API_URL/api/status" | grep "ok"
+            then
+                exit 0
+            else
+                exit 1
+            fi
       - run:
           name: Frontend smoke test.
           command: |
-            # your code here
+            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
+            echo $URL
+            if curl -s $URL | grep "Welcome"
+            then
+                # Change this to 0 after the job fails
+              exit 1
+            else
+              exit 1
+            fi
+      - destroy-environment
+      - revert-migrations
 
   cloudfront-update:
     docker:
@@ -314,10 +357,12 @@ jobs:
       - run:
           name: Update cloudfront distribution
           command: |
+            # Change the initial stack name, as applicable to you
             aws cloudformation deploy \
-            --template-file cloudfront.yml \
-            --stack-name production-distro \
-            --parameter-overrides PipelineID="mybucket-${CIRCLE_WORKFLOW_ID:0:7}" 
+                      --template-file .circleci/files/cloudfront.yml \
+                      --stack-name InitialStack \
+                      --parameter-overrides WorkflowID="udapeople-${CIRCLE_WORKFLOW_ID:0:7}" \
+                      --tags project=udapeople
 
   cleanup:
     docker:
